import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Decorder from '../components/decorder'

export default function Decord() {
  return (
    <div className={styles.container}>
      <Head>
        <title>URL デコーダー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Decorder />
    </div>
  )
}
