version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app
    ports:
      - "3000:3000"
